### ISSUE TITLE
launch error ?

### ISSUE THREAD

**Issue by Abduoit** [marcoesposito1988/easy_handeye_demo#2]
Hi

I am getting this error, I cloned the whole package, did I miss something ?

could you be please look at it ?

```
abdulrahman@abdu:~$ roslaunch easy_handeye_demo calibrate.launch
... logging to /home/abdulrahman/.ros/log/fe48c316-004f-11e8-a775-e09d31097f54/roslaunch-abdu-9677.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

redefining global property: pi
when processing file: /home/abdulrahman/catkin_ws/src/universal_robot/ur_description/urdf/ur5.urdf.xacro
included from: /home/abdulrahman/catkin_ws/src/universal_robot/ur_description/urdf/ur5_joint_limited_robot.urdf.xacro
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 746, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 718, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 682, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 587, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 316, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 329, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 142, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 188, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: easy_handeye
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/abdulrahman/catkin_ws/src
ROS path [2]=/opt/ros/indigo/share
ROS path [3]=/opt/ros/indigo/stacks

```

**Comment by marcoesposito1988** [comment]
Hello @Abduoit,

please note that the package is not in a finished state.

However, the error happens because you didn't also clone the easy_handeye repository in your catkin workspace src folder.

**Comment by Abduoit** [comment]
yes I did clone it and catkin_make as well

you can check here

```
abdulrahman@abdu:~$ cd catkin_ws/src/easy_handeye_demo/launch/
abdulrahman@abdu:~/catkin_ws/src/easy_handeye_demo/launch$ ls
calibrate.launch
abdulrahman@abdu:~/catkin_ws/src/easy_handeye_demo/launch$ 
```

**Comment by marcoesposito1988** [comment]
This is easy_handeye_demo; I meant easy_handeye (https://github.com/marcoesposito1988/easy_handeye)

**Comment by Abduoit** [comment]
Thanks @marcoesposito1988 

I run the demo, I got two rviz windows 

when I press compute in gui window I always get zeros

**Comment by marcoesposito1988** [comment]
Are you moving the robot around and taking samples at different positions before running the algorithm?

**Comment by lucamarchionna** [comment]
Hi everyone, I am experiencing the same problem. Basically, I have launched all the needed files to perform calibration, according to the step you described. However, when I click on the 'check starting pose' button, it returns "Cannot calibrate from current position". For sure, I am skipping some important steps but I don't know which one. In addition, I am able to successfully move the robot within RViZ.
Below, you can find the launch file and a photo of the result. 

Photo:
![forum_easyendeye](https://user-images.githubusercontent.com/73609459/124603438-39a5d100-de6a-11eb-9539-8e3594e6cdad.png)

Launch file:
![forum_launch](https://user-images.githubusercontent.com/73609459/124603723-85f11100-de6a-11eb-8097-89d064a3cf81.png)

**Comment by marcoesposito1988** [comment]
Hi @lucamarchionna,

when you check the starting pose, the software plans a movement from the current position of the robot to a series of poses around it, obtained by rotating the end effector about each axis in each direction, and translating it in every direction. If at least one pose can't be reached, or would require a very large movement (hence unexpected and dangerous), you get this error. 

Any 6-DOF robot should have no problems if starting within its dexterous workspace. If you encounter problems, you can try reducing the rotation and translation (there should be launch arguments for that).

If all fails, you can move the robot by hand (there is another argument for that case).
